### ISSUE TITLE
Still some improvement can do

### ISSUE THREAD

**Issue by jomaf1010** [denysvitali/thebestmotherfuckingwebsite#10]
~minify main.fucking.js
~gzip assets

cheers!

**Comment by denysvitali** [comment]
[X] GZIP
[ ] Minify main.fucking.js

I'll correct the gulp file to minify the js file

**Comment by denysvitali** [comment]
Actually, I think I won't minify the `main.fucking.js` file, since it is funny to read. Minifying it will probably reduce the readiness and the variable / function names will be gone.

I'm going to close this issue, if you don't agree with my choice feel free to comment here or open a new issue 👍
