### ISSUE TITLE
Consider a second color for visited links

### ISSUE THREAD

**Issue by hellerbarde** [denysvitali/thebestmotherfuckingwebsite#11]
While I agree that the default blue and violet look kinda horrible, the visibly visited links concept is still a good and useful idea.

As a suggestion, consider Maroon from this website: http://clrs.cc/ (#85144b)

**Comment by denysvitali** [comment]
Thanks for your suggestion, I'll implement the color you proposed :)

**Comment by denysvitali** [comment]
I wrote an elaborate answer before, but I accidentally closed the tab and lost everything (fml).
By the way: I changed the color as suggested, but tweaked it a bit. I chose the [#941352](https://www.colorhexa.com/941352) color because I thought yours was a bit too violetish.

If you don't like it, and want to propose another change, feel free to reopen this issue :)

The changes are now live at [thebestmotherfucking.website](https://thebestmotherfucking.website/)
![screenshot from 2017-07-14 15-21-58](https://user-images.githubusercontent.com/4939519/28214292-f1686298-68a9-11e7-9578-35a74e7ac771.png)
Please note that the colors in this image may not be accurate, since it is in JPEG format, it is better to see the changes for yourself on TBMFW.

**Comment by hellerbarde** [comment]
No, as long as the colors are visually distinguishable, i am happy. Thanks for the consideration.

On July 14, 2017 3:35:39 PM GMT+02:00, Denys Vitali <notifications@github.com> wrote:
>I wrote an elaborate answer before, but I accidentally closed the tab
>and lost everything (fml).
>By the way: I changed the color as suggested, but tweaked it a bit. I
>chose the [#941352](https://www.colorhexa.com/941352) color because I
>thought yours was a bit too violetish.
>
>If you don't like it, and want to propose another change, feel free to
>reopen this issue :)
>
>The changes are now live at
>[thebestmotherfucking.website](https://thebestmotherfucking.website/)
>![screenshot from 2017-07-14
>15-21-58](https://user-images.githubusercontent.com/4939519/28214292-f1686298-68a9-11e7-9578-35a74e7ac771.png)
>Please note that the colors in this image may not be accurate, since it
>is in JPEG format, it is better to see the changes for yourself on
>TBMFW.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/denysvitali/thebestmotherfuckingwebsite/issues/11#issuecomment-315360961

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xxbeta21** [comment]
I HATE MAROON!!?!?!?!!
WHAT IS THIS, YOU ARE KILLING CHILDREN!
please make it dark red. thx

**Comment by xxbeta21** [comment]
> 
> 
> I HATE MAROON!!?!?!?!!
> WHAT IS THIS, YOU ARE KILLING CHILDREN!
> please make it dark red. thx

update: preferably #990012

**Comment by Rigidity** [comment]
I swear to god change the color my eyes are literally bleeding out right now

**Comment by denysvitali** [comment]
What color would you suggest instead?

**Comment by Rigidity** [comment]
I was joking haha the site said to complain about it

**Comment by jamestomasino** [comment]
Maroon is pretty, but on black, even with "extra contrast" enabled, we have insufficient color contrast for accessibility:

Color and Contrast  2.20

Does not meet WCAG standards for accessible text. [Learn more](https://developer.mozilla.org/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast)

**Comment by jeremiahsherrill** [comment]
the background should be green with pink text... everyone knows that how you build a kick ass website, I would also include a photo of some toast.

**Comment by LynX-gh** [comment]
I came here specifically to complain about the maroon bullshit. Change that shit absolute trash

**Comment by denysvitali** [comment]
What should we change it to?
Also, we can't seem to please everyone, the maroon was chosen because of the fact that some people didn't like the light blue

**Comment by LynX-gh** [comment]
Its fine, I complained because the website told me to complain

**Comment by Civermau** [comment]
That motherfuckingwebsite can't be the best motherfucking website with that motherfucking brown color, should use #99FFBC to make that shitty motherfuckingwebsite the actual bestmotherfuckingwebsite

**Comment by Skywalker8510** [comment]
Well looks like the link brought me to the place to complain. That motherfuckingwebsite thats the bestmotherfuckingwebsite has the worst motherfucking visited link color. Visited links should obviously be same same motherfucking color as the motherfucking background. 

(This is satire. Just like all the motherfucking websites.)
