### ISSUE TITLE
Justified text looks bad on mobile.

### ISSUE THREAD

**Issue by glodime** [denysvitali/thebestmotherfuckingwebsite#12]
Mobile viewing is hampered by the justified text layout.

**Comment by denysvitali** [comment]
Thanks for opening this issue: I'll look into it as soon as I can

**Comment by jmossetc** [comment]
Well actually I think that justified text is a bad idea for most websites, be it on mobile or desktop, as any web designer would tell you. 

https://www.google.com/search?q=justify+text+websites&oq=justify+text+websites
