### ISSUE TITLE
Inverted mode does not work

### ISSUE THREAD

**Issue by seanvree** [denysvitali/thebestmotherfuckingwebsite#13]
Inverted mode doesn't work motherfucker.

**Comment by denysvitali** [comment]
Seems to work here:
![screenshot from 2017-08-08 16-34-56](https://user-images.githubusercontent.com/4939519/29077093-8d161d1e-7c57-11e7-98d6-d5d447514a31.png)

What browser / OS / device are you using?

**Comment by seanvree** [comment]
It's hosted behind IIS on Windows 10x .  Been trying with Chrome, but looks like it DOES work with IE???

my version is live:

http://seanvree . com / thebestmotherfuckingwebsite/


![image](https://user-images.githubusercontent.com/8906637/29077735-a065cb34-7c0d-11e7-820c-e8f3d0d0b798.png)

**Comment by CapacitorSet** [comment]
It works just fine on my FF 54.0 on Ubuntu. Does the Developer console show anything?

**Comment by denysvitali** [comment]
I really don't understand the problem @seanvree : the browser on the left has the "Inverted mode" enabled, the one on the right does not

**Comment by seanvree** [comment]
Yeah, when I click on the inverted mode in Chome, it doesn't work, nothing happens.  The one on the right is IE, and it DOES work.  

NBD just wondering.

**Comment by denysvitali** [comment]
Sorry, I didn't understood the problem. Which version of Chrome are you using?

**Comment by denysvitali** [comment]
@seanvree Are you still facing the issue?

**Comment by denysvitali** [comment]
I'm closing the issue since it didn't got a reply from the author. Feel free to reopen it if you need.
