### ISSUE TITLE
Remove js dependency from site

### ISSUE THREAD

**Issue by kandeshvari** [denysvitali/thebestmotherfuckingwebsite#19]
it's not suitable for "thebestmotherfuckingwebsite"

**Comment by denysvitali** [comment]
What JS dependency?  
Currently on TBMFW we use JS to do the following things:
- Contrast / Inverted Mode  
- Color rainbow  
- [jQuery prank](https://thebestmotherfucking.website/js/jquery-2.2.4.min.js) - 
  
I agree on the fact that the first two features can be rewritten using only CSS-rules, but tbh that doesn't look like a huge performance improvement - and it may break compatibility on some devices that still doesn't support CSS3.  
PRs are welcome though. I'm also open to proposals.

**Comment by denysvitali** [comment]
Closing this since since it didn't get any answer. Feel free to reopen the issue if you want to answer :+1:

**Comment by ScoreUnder** [comment]
Currently all CSS depends on JS. On my 1440p monitor, the HTML5 logo displays in 2492x2492px, just a stone's throw from the "Size matters, yeah, but don't exaggerate" heading (which itself is 33px tall).

There are no margins, the text is #000000 black, and all the links are the browser's built-in colour. I assume these are meant to be filled in with CSS, but they are not filled in without also using JavaScript.

This is in contrast to the "bettermotherfuckingwebsite", where the styles display as expected.

**Comment by denysvitali** [comment]
Meh, this is in contrast w/ #28

**Comment by denysvitali** [comment]
Fixed in ea3095d
