### ISSUE TITLE
Update jQuery

### ISSUE THREAD

**Issue by Jackymancs4** [denysvitali/thebestmotherfuckingwebsite#21]
Hello @denysvitali 
Thebestmotherfuckingwebsite shouldn't use a version of jQuery that doesn't receive patches anymore.

I suggest to update to the last one (v3.3.1 at time of writing), and then brag about it. Something like:

```javascript
/* NO, really, NOBODY NEEDS TO INCLUDE A FUCKING FRAMEWORK TO MAKE A COOL WEBSITE. */
console.log('Don\'t worry, no jQuery was used in this website.');
console.log('But if it was, it would have been the last supported version. Security and maintenance are important!');
var $ = function(){this.fancyRainbow = function(){return this;};this.html = function(){return this;};return this;};
```

You know, being a good role model for developers 👍 
If you like, I can make a PR by the end of the day.

**Comment by denysvitali** [comment]
117 more characters? :fearful:

**Comment by C-Lodder** [comment]
Just remove jQuery! We're coming up to 2019 for crying out loud

**Comment by denysvitali** [comment]
Updated to 3.5.1 in an upcoming commit
