### ISSUE TITLE
No cache-control header present

### ISSUE THREAD

**Issue by strburst** [denysvitali/thebestmotherfuckingwebsite#23]
I read about the "Cache Control" header in the website.

> It includes a Cache-Control header, so you don't waste your precious bandwidth if you visit the website more than once

I got curious and checked the headers out with curl to see what they looked like, and found that there doesn't seem to be a cache control header anywhere. Here are the headers for <https://thebestmotherfucking.website> and <https://pages.github.com> for comparison.

```shell
% curl -I https://thebestmotherfucking.website
HTTP/2 200
server: nginx/1.15.1
date: Wed, 11 Jul 2018 01:31:35 GMT
content-type: text/html
content-length: 12499
last-modified: Wed, 27 Dec 2017 12:28:01 GMT
etag: "5a4391d1-30d3"
accept-ranges: bytes

% curl -I https://pages.github.com
HTTP/2 200
server: GitHub.com
content-type: text/html; charset=utf-8
last-modified: Mon, 02 Jul 2018 18:07:44 GMT
access-control-allow-origin: *
expires: Wed, 11 Jul 2018 00:26:18 GMT
cache-control: max-age=600
x-github-request-id: *REDACTED*
accept-ranges: bytes
date: Wed, 11 Jul 2018 01:31:38 GMT
via: 1.1 varnish
age: 0
x-served-by: cache-ewr18124-EWR
x-cache: MISS
x-cache-hits: 0
x-timer: S1531272698.232084,VS0,VE9
vary: Accept-Encoding
x-fastly-request-id: *REDACTED*
content-length: 14723

```

I also checked for a `<meta http-equiv="Cache-Control" content="...">` tag and didn't find one.

Fixing this is probably a matter of revisiting the nginx configuration. Also see #5.

(P.S. I would recommend something like `public, max-age=600`, which is appropriate for a static website.)

**Comment by denysvitali** [comment]
Thanks for the issue.  
Actually, the problem was fixed in #5 a long time ago, but I had to switch over to a new server and forgot some lines of the config (such as the gzipping part and the cache control).  

I'll fix it ASAP, thanks for the tips!

**Comment by denysvitali** [comment]
Fixed!

```
dvitali@denvit-ws1:~ $ curl -H "Accept-Encoding: gzip" 'https://thebestmotherfucking.website/' --head            
HTTP/2 200 
server: nginx
date: Wed, 11 Jul 2018 08:16:47 GMT
content-type: text/html
last-modified: Wed, 27 Dec 2017 12:28:01 GMT
vary: Accept-Encoding
etag: W/"5a4391d1-30d3"
expires: Thu, 01 Jan 1970 00:00:01 GMT
cache-control: no-cache
x-frame-options: SAMEORIGIN
referrer-policy: same-origin
content-encoding: gzip

dvitali@denvit-ws1:~ $ curl -H "Accept-Encoding: gzip" 'https://thebestmotherfucking.website/css/main.css' --head
HTTP/2 200 
server: nginx
date: Wed, 11 Jul 2018 08:16:49 GMT
content-type: text/css
last-modified: Wed, 27 Dec 2017 12:28:01 GMT
vary: Accept-Encoding
etag: W/"5a4391d1-d42"
expires: Sat, 21 Jul 2018 08:16:49 GMT
cache-control: max-age=864000
x-frame-options: SAMEORIGIN
referrer-policy: same-origin
content-encoding: gzip
```

Feel free to reopen the issue if you think something is still missing, thank you for your help :rocket:

**Comment by strburst** [comment]
Looks great, thanks for fixing it really fast! 🏁🏎️🏁
