### ISSUE TITLE
Load assets correctly

### ISSUE THREAD

**Issue by C-Lodder** [denysvitali/thebestmotherfuckingwebsite#28]
Using defer and async do not properly lazy load your CSS and JS as it's still technically render blocking.

### Solution (ES6):

Add the following to just before the closing `</body>` tag

```
<script>
	for (const css of [
	  "css/main.css",
	]) {
	  const link = document.body.appendChild(document.createElement("link"));
	  link.rel = 'stylesheet';
	  link.href = css;
	}

	for (const js of [
	  "//piwik.vps.denv.it/piwik.js",
	  "js/jquery-2.2.4.min.js",
	  "js/main.fucking.js",
	]) {
	  const script = document.body.appendChild(document.createElement("script"));
	  script.async = false;
	  script.src = js;
	}
</script>
```

**Comment by denysvitali** [comment]
[Oh, I wish this was possible today 😞](https://kangax.github.io/compat-table/es6/#ie11)

**Comment by C-Lodder** [comment]
@danielquinn But the thebestmotherfuckingwebsite doesn't support IE :D 

ES5 version if you like:

``
<script>
	var css = [
		"css/main.css"
	];
	for (var i = 0; i < css.length; i++) {
		var link = document.body.appendChild(document.createElement("link"));
		link.rel = 'stylesheet';
		link.href = css[i];
	}

	var js = [
		"//piwik.vps.denv.it/piwik.js",
		"js/jquery-2.2.4.min.js",
		"js/main.fucking.js",
	];
	for (var i = 0; i < js.length; i++) {
		var script = document.body.appendChild(document.createElement("script"));
		script.async = false;
		script.src = js[i];
	}
</script>
```

**Comment by denysvitali** [comment]
The fact is that I do not plan to support IE 11, but at least when the other JS functions / CSS directives aren't available on IE it fails gracefully. But with your first proposal it fails in a very harsh way (from my understanding, it doesn't load the CSS, nor the JS, making the website look like motherfuckingwebsite.com )

Your second snippet looks way much better, do you care making a PR?

**Comment by C-Lodder** [comment]
@denysvitali Sure, I'll submit a PR. Need to look into you HTML preprocessor first :)

**Comment by C-Lodder** [comment]
@denysvitali PR: https://github.com/denysvitali/thebestmotherfuckingwebsite/pull/29

Closing
