### ISSUE TITLE
Default inverted mode for macOs users with dark theme

### ISSUE THREAD

**Issue by alsoknownasdrew** [denysvitali/thebestmotherfuckingwebsite#32]
Hi! I love your motherfucking website and I noticed a little room for improvement:

You can set the dark mode automatically for macOS users who have enabled dark mode on their machines with `prefers-color-scheme: dark` media query as you can see in [this blogpost](https://css-tricks.com/dark-modes-with-css/)

I could work on it if you decide to implement this feature and don't have time to do it by yourself.

**Comment by denysvitali** [comment]
Sorry for the long wait, I'm now pushing a commit that fixes exactly this issue :+1:

**Comment by denysvitali** [comment]
Feel free to re-open the issue if the problem persists (edits will go live soon)
