### ISSUE TITLE
remove third-party requests like Google Fonts

### ISSUE THREAD

**Issue by baptx** [denysvitali/thebestmotherfuckingwebsite#34]
The best mother fucking website should be focused on privacy too by not making third-party requests like Google Fonts ;)

**Comment by denysvitali** [comment]
Switched to [typeface-open-sans](https://www.npmjs.com/package/typeface-open-sans). Thanks for opening this issue and sorry for the delay in fixing it :+1: .

Feel free to re-open the issue at any time if you think that the issue isn't fixed
