### ISSUE TITLE
Missing favicons throughout devices and platforms

### ISSUE THREAD

**Issue by rhazor** [denysvitali/thebestmotherfuckingwebsite#35]
Just run this https://realfavicongenerator.net/favicon_checker

Use this https://realfavicongenerator.net/ to generate favicons (go through settings).

I want to have this website on my phone's home screen with its official icon, I visit this website every morning when I wake up for inspiration. Unacceptable, motherfucker.

**Comment by denysvitali** [comment]
That will cost us a couple of kBs. I'll make sure to add it though, so that I can satisfy your needs 🎉

**Comment by rhazor** [comment]
Draw that cat from polygons.

**Comment by denysvitali** [comment]
LOL, I'll make sure to transform it to an SVG.  
  
By the way, what do you think it will be more suitable as a favicon? What icon represents best the website?  
  
Should I use a big black "M" over a white background?

**Comment by rhazor** [comment]
Need to come up with official logo or something.

**Comment by decadentsoup** [comment]
> LOL, I'll make sure to transform it to an SVG.

I wanted to see how easy that'd be. Only took five minutes to make this little number:

https://www.dropbox.com/s/9oxou7sebm3qxlc/cat.svg

A whopping 276.2 KiB though!

**Comment by denysvitali** [comment]
Feel free to rate the icons: I've created them with https://favicon.io/favicon-generator/
