### ISSUE TITLE
CA is not green anymore

### ISSUE THREAD

**Issue by jaggli** [denysvitali/thebestmotherfuckingwebsite#37]
Recently most major browsers removed the green color from browsers addressbars
https://github.com/denysvitali/thebestmotherfuckingwebsite/blob/master/src/pug/index.pug#L45

So this text might need some rework.

**Comment by denysvitali** [comment]
Indeed. Fixing it

**Comment by denysvitali** [comment]
I hope that this fixes the issue. Feel free to re-open this issue if you feel that it wasn't fixed by my commit (:
