### ISSUE TITLE
Use <figure>

### ISSUE THREAD

**Issue by theandrewbailey** [denysvitali/thebestmotherfuckingwebsite#38]
Cat image and caption should be contained in a `<figure>` element.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure

`<figure><img src="img/cat.jpg" title="A nice and cute cat"><figcaption>A cat, just to keep the context of the website.</figcaption></figure>`

**Comment by denysvitali** [comment]
Indeed they should! Thank you for pointing it out!

**Comment by denysvitali** [comment]
Fixed with my most recent commit, feel free to re-open the issue if you don't like it :+1:
