### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by beardog108** [denysvitali/thebestmotherfuckingwebsite#5]
This is a pretty good website, but there are some things I can think of to improve it:

- [x] Enable http/2
- [x] Set a cache-control header
- [x]  [Enable CORS](http://enable-cors.org/) (fairly debatable)
- [x] Strip the 'server' header, which is a pointless advertisement
- [x] Switch to Piwik for stats or just parse your log file (I'm willing to wager that many people that visit this website are using uBlock Origin or some other addon that blocks analytic scripts anyway)

I don't think you can remove 'server' without compiling nginx yourself, but the 'Caddy' web server can & will make your life easier anyway: https://caddyserver.com/

**Comment by denysvitali** [comment]
Thanks, I'll make the suggested changes :)

**Comment by denysvitali** [comment]
I have to add that unfortunately there is no way to remove the `Server` header without recompiling nginx, I've added [ŧhis](https://github.com/denysvitali/thebestmotherfuckingwebsite/blob/master/partial-nginx.conf#L6) hoping it would be better for you (the header now shows `Server: nginx`)
