### ISSUE TITLE
The website could use some security HTTP headers

### ISSUE THREAD

**Issue by xaban2** [denysvitali/thebestmotherfuckingwebsite#51]
Currently it gets a "F" grade: [scan results](https://securityheaders.com/?q=https%3A%2F%2Fthebestmotherfucking.website%2F&hide=on&followRedirects=on)

**Comment by denysvitali** [comment]
Nice catch,  this was already solved in the past but I recently switched to a new host and forgot to apply the config. Give me 10 minutes

**Comment by denysvitali** [comment]
Solved:
![20201113_15h59m54s_grim](https://user-images.githubusercontent.com/4939519/99086094-559def00-25c9-11eb-855e-bfab83b933ee.png)

I'm still missing the `Permissions-Policy` header, but I decided not to implement it since it is still a draft (:
