### ISSUE TITLE
Contrast too low

### ISSUE THREAD

**Issue by 5ilver** [denysvitali/thebestmotherfuckingwebsite#6]
Hard to read without my glasses on. Please consider 333 or darker for text.

#8

**Comment by abluejelly** [comment]
The #555 is WCAG 2.0 AAA compliant at all sizes.... but the blockquotes at #777 are only AA compliant (AAA with same caveat as the links), and the #2980b9 and #16a085 on the links is only AA compliant at 18pt / bold 14pt.

The #555 is fine, it's the other two that are too low-contrast. I'd suggest bumping the blockquotes to #557 (still distinguished, but reclaims AAA any size), and the links to #07a and #075 (both AA all sizes, AAA 18pt/b14pt) while also ditching 3 locs each in the css.

**Comment by denysvitali** [comment]
Thanks for the pull request @5ilver , I really appreciate that, but (as already stated in the website, see "Put even less contrast") I think that's too much contrast.

Thanks to @abluejelly for his effort, I'll correct the website accordingly

**Comment by denysvitali** [comment]
I'm closing the issue, in a few minutes I'll push the changes to thebestmotherfucking.website , if you still don't like it / find it difficult to read let me know 👍
