### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by unbeatable-101** [denysvitali/thebestmotherfuckingwebsite#67]
<img width="1093" alt="Screen Shot 2021-07-08 at 15 56 15" src="https://user-images.githubusercontent.com/58151048/124982758-15cac280-e005-11eb-917c-b4d7ebf53faf.png">

**Comment by denysvitali** [comment]
Hey! Everything looks fine here, maybe the server had a quick hiccup.

Can you please check again?

**Comment by unbeatable-101** [comment]
It's working now
