### ISSUE TITLE
The UL at the bottom contains an errant empty LI

### ISSUE THREAD

**Issue by Kadigan** [denysvitali/thebestmotherfuckingwebsite#90]
Exactly what it says in the title.

Here's an image, just because GH allows it:

![image](https://github.com/denysvitali/thebestmotherfuckingwebsite/assets/16637976/f727c941-be82-4e06-8cd4-fe1b9e2c93b1)

And yes, I'll consider it _hilarious_ if you reuse it to _credit me pointing it out_ (the image above comes in handy as a historical record of it - for reference, and to complete the joke).

**Comment by denysvitali** [comment]
This doesn't seem to be an issue anymore, thanks for reporting it though!
I'll add your name to the credits anyways :D

**Comment by denysvitali** [comment]
Fixed in 438dd03
